// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XUPDATE_N_H
#define XUPDATE_N_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xupdate_n_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XUpdate_n_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XUpdate_n;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XUpdate_n_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XUpdate_n_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XUpdate_n_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XUpdate_n_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XUpdate_n_Initialize(XUpdate_n *InstancePtr, u16 DeviceId);
XUpdate_n_Config* XUpdate_n_LookupConfig(u16 DeviceId);
int XUpdate_n_CfgInitialize(XUpdate_n *InstancePtr, XUpdate_n_Config *ConfigPtr);
#else
int XUpdate_n_Initialize(XUpdate_n *InstancePtr, const char* InstanceName);
int XUpdate_n_Release(XUpdate_n *InstancePtr);
#endif

void XUpdate_n_Start(XUpdate_n *InstancePtr);
u32 XUpdate_n_IsDone(XUpdate_n *InstancePtr);
u32 XUpdate_n_IsIdle(XUpdate_n *InstancePtr);
u32 XUpdate_n_IsReady(XUpdate_n *InstancePtr);
void XUpdate_n_EnableAutoRestart(XUpdate_n *InstancePtr);
void XUpdate_n_DisableAutoRestart(XUpdate_n *InstancePtr);

void XUpdate_n_Set_num(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_num(XUpdate_n *InstancePtr);
void XUpdate_n_Set_stable_para_offset(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_stable_para_offset(XUpdate_n *InstancePtr);
void XUpdate_n_Set_input00_V(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_input00_V(XUpdate_n *InstancePtr);
void XUpdate_n_Set_input01_V(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_input01_V(XUpdate_n *InstancePtr);
void XUpdate_n_Set_output0_offset(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_output0_offset(XUpdate_n *InstancePtr);
void XUpdate_n_Set_output1_offset(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_output1_offset(XUpdate_n *InstancePtr);
void XUpdate_n_Set_output2_s(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_output2_s(XUpdate_n *InstancePtr);
void XUpdate_n_Set_output3_s(XUpdate_n *InstancePtr, u32 Data);
u32 XUpdate_n_Get_output3_s(XUpdate_n *InstancePtr);

void XUpdate_n_InterruptGlobalEnable(XUpdate_n *InstancePtr);
void XUpdate_n_InterruptGlobalDisable(XUpdate_n *InstancePtr);
void XUpdate_n_InterruptEnable(XUpdate_n *InstancePtr, u32 Mask);
void XUpdate_n_InterruptDisable(XUpdate_n *InstancePtr, u32 Mask);
void XUpdate_n_InterruptClear(XUpdate_n *InstancePtr, u32 Mask);
u32 XUpdate_n_InterruptGetEnabled(XUpdate_n *InstancePtr);
u32 XUpdate_n_InterruptGetStatus(XUpdate_n *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
