// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// ctrl_bus
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of num
//        bit 31~0 - num[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of stable_para_offset
//        bit 31~0 - stable_para_offset[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of input00_V
//        bit 31~0 - input00_V[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of input01_V
//        bit 31~0 - input01_V[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of output0_offset
//        bit 31~0 - output0_offset[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of output1_offset
//        bit 31~0 - output1_offset[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of output2_s
//        bit 31~0 - output2_s[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of output3_s
//        bit 31~0 - output3_s[31:0] (Read/Write)
// 0x4c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XUPDATE_N_CTRL_BUS_ADDR_AP_CTRL                 0x00
#define XUPDATE_N_CTRL_BUS_ADDR_GIE                     0x04
#define XUPDATE_N_CTRL_BUS_ADDR_IER                     0x08
#define XUPDATE_N_CTRL_BUS_ADDR_ISR                     0x0c
#define XUPDATE_N_CTRL_BUS_ADDR_NUM_DATA                0x10
#define XUPDATE_N_CTRL_BUS_BITS_NUM_DATA                32
#define XUPDATE_N_CTRL_BUS_ADDR_STABLE_PARA_OFFSET_DATA 0x18
#define XUPDATE_N_CTRL_BUS_BITS_STABLE_PARA_OFFSET_DATA 32
#define XUPDATE_N_CTRL_BUS_ADDR_INPUT00_V_DATA          0x20
#define XUPDATE_N_CTRL_BUS_BITS_INPUT00_V_DATA          32
#define XUPDATE_N_CTRL_BUS_ADDR_INPUT01_V_DATA          0x28
#define XUPDATE_N_CTRL_BUS_BITS_INPUT01_V_DATA          32
#define XUPDATE_N_CTRL_BUS_ADDR_OUTPUT0_OFFSET_DATA     0x30
#define XUPDATE_N_CTRL_BUS_BITS_OUTPUT0_OFFSET_DATA     32
#define XUPDATE_N_CTRL_BUS_ADDR_OUTPUT1_OFFSET_DATA     0x38
#define XUPDATE_N_CTRL_BUS_BITS_OUTPUT1_OFFSET_DATA     32
#define XUPDATE_N_CTRL_BUS_ADDR_OUTPUT2_S_DATA          0x40
#define XUPDATE_N_CTRL_BUS_BITS_OUTPUT2_S_DATA          32
#define XUPDATE_N_CTRL_BUS_ADDR_OUTPUT3_S_DATA          0x48
#define XUPDATE_N_CTRL_BUS_BITS_OUTPUT3_S_DATA          32

